-- My Script generated by My Workbench
-- Sat May 20 12:54:48 2023
-- Model: New Model    Version: 1.0
-- My Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD__MODE=@@_MODE, _MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trapwire
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trapwire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trapwire` DEFAULT CHARACTER SET utf8 ;
USE `Trapwire` ;

-- -----------------------------------------------------
-- Table `Trapwire`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Marca` (
  `idMarca` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trapwire`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Modelo` (
  `idModelo` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_Modelo_Marca1_id` (`Marca_idMarca` ) VISIBLE,
  CONSTRAINT `fk_Modelo_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Trapwire`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trapwire`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `nomesocial` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `endereço` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trapwire`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trapwire`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Produto` (
  `idProduto` INT NOT NULL,
  `desc` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `Fornecedor_idFornecedor`),
  INDEX `fk_Produto_Fornecedor1_id` (`Fornecedor_idFornecedor` ) VISIBLE,
  INDEX `fk_Produto_Fornecedor1_id` (`Fornecedor_idFornecedor` ) VISIBLE,
  INDEX `fk_Produto_Marca1_id` (`Marca_idMarca` ) VISIBLE,
  INDEX `fk_Produto_Categoria1_id` (`Categoria_idCategoria` ) VISIBLE,
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `Trapwire`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Trapwire`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `Trapwire`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trapwire`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `endereço` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trapwire`.`Logistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trapwire`.`Logistica` (
  `idLogistica` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `quant` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idLogistica`, `Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Logistica_Produto_id` (`Produto_idProduto` ) VISIBLE,
  INDEX `fk_Logistica_Estoque1_id` (`Estoque_idEstoque` ) VISIBLE,
  CONSTRAINT `fk_Logistica_Produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `Trapwire`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Logistica_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `Trapwire`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET _MODE=@OLD__MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;